# Многомерные массивы в Numpy

In [2]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

создание из кортежа

In [7]:
c = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [8]:
b = np.array(c)

In [9]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
type(b)

numpy.ndarray

In [11]:
b = np.array(a, dtype = float) # фргумент dtype задает тип данных в массиве

In [ ]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9.9]

In [12]:
b = np.array(a, dtype=int)

In [13]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.array(a, dtype = float)

In [15]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
b = np.array(a, dtype=str)

In [18]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

если в массиве есть данные str, float. но не указан параметр dtype  то весь массив преобретает значения строки или плавающей запятой

In [17]:
b.dtype

dtype('<U1')

In [19]:
b[1]

'1'

In [20]:
b[2]

'2'

смотрим размерность массива команды "b.ndim" и b.shape

In [21]:
b.ndim

1

In [22]:
b.shape

(10,)

создадим двумерный массив

In [25]:
b = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
b.shape

(3, 10)

(первое число в матрице три строки. второе 10 столбцов)

In [28]:
b.size #смотрим общее число элементов

30

In [29]:
b[1, 0] #получаем доступ к элементом массива матрица двумерная поэтому указываем два индекса

10

In [30]:
b[1, -9]

11

In [31]:
# делаем срез из двумерного массива обы полуилась матрица меньшего размера

b[0:2, 0:3] #две первых строки и три первых столбца [с нулевой строи вклюительно по вторую строку невключительно и с нулевого столбца включительно по третий столбец невключительно]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [32]:
# если счет ведется с нулевого индекса можно его не писать

b[:2, :3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [33]:
# если делаем срез включающий последнии элемент ничего не пишем после двоеточия
b[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [34]:
#матрица с это представления view ссылки на отдельные елементы массива b
c = b[1:, 5:]

In [35]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [36]:
# если меняем что-то в матрице с то этот елемент меняется и в матрице b
c[1, 4] = 999

In [37]:
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [38]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [39]:
#если хотим чтобы массив c был новым независимым обьектом то применяем метод copy
c = b[1:, 5:].copy()

In [40]:
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

## Типы данных

самые распространенные типы данных в нампай это float=32 and float=64
а также int = 32 and int = 64 инт 64 занимает в два раза больше места
но если в модуле есть числа больше чем 2 миллиарда лучше его использовать

## Numpy  в линейной алгебре

In [3]:
# задаем векторы, должны быть одной размерности
a = np.array([0, 1, 2, 3, 4])



In [4]:
b = np.array([5, 6, 7, 8, 9])

In [5]:
a.size

5

In [6]:
b.size

5

In [7]:
a.shape

(5,)

In [8]:
b.shape

(5,)

In [14]:
# сложение векторов
c = a + b

In [15]:
c

array([ 5,  7,  9, 11, 13])

In [16]:
# лучше использовать метод add чтобы не было путанницы с библеотеками пайтон

c = np.add(a, b)

In [17]:
c

array([ 5,  7,  9, 11, 13])

In [18]:
# выитание векторов
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])


In [20]:
d = a - b
d

array([ 2, -1,  1,  3,  0])

In [21]:
# лучше использовать метод subtract
d = np.subtract(a, b)
d

array([ 2, -1,  1,  3,  0])

In [22]:
# также размерность должна совпадать

a.shape == b.shape


True

In [2]:
# умножение вектора на скаляр
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [4]:
c = a * 2
c

array([10,  8, 16,  8,  6])

In [5]:
c = -10 * a
c

array([-50, -40, -80, -40, -30])

In [6]:
c = 0,5 * a
c

(0, array([25, 20, 40, 20, 15]))

In [ ]:
# лучше использовать методы dot and multiply

In [7]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [8]:
# метод
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [9]:
#функция
np.dot(-10, a)

array([-50, -40, -80, -40, -30])

In [10]:
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

In [ ]:
# сколярное произведение векторов 

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [12]:
a.shape

(3,)

In [13]:
b.shape

(3,)

In [14]:
sp = a[0]*b[0] + a[1]*b[1] +a[2]*b[2]
sp

32

In [15]:
a @ b

32

In [16]:
sp = np.dot(a, b)
sp

32

In [ ]:
# Операции с матрицами

In [18]:
A = np.array([[0,1],
             [2,3],
             [4,5]])

In [19]:
B = np.array([[6,7],
              [8,9],
              [10,11]])

In [20]:
A.shape == B.shape

True

In [21]:
A.shape

(3, 2)

In [22]:
B.shape

(3, 2)

In [24]:
# сложение матриц
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [25]:
# лучше использоывть метод add
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [27]:
A = np.array([[11, 13],
             [16, 19],
             [8, 15]])

In [28]:
B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

In [29]:
# вычитание матриц
D = A - B
D

array([[ 5,  6],
       [ 8, 10],
       [-2,  4]])

In [30]:
D = np.subtract(A, B)
D

array([[ 5,  6],
       [ 8, 10],
       [-2,  4]])

In [ ]:
# Умножение матриц на скаляр

In [31]:
X = np.array([[1, 2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [33]:
Y = X * 3
Y

array([[ 3,  6],
       [ 9, 12]])

In [34]:
Y = np.dot(X, 3)
Y

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
# Уможение матриц 

In [35]:
X1 = np.array([[1, 2],[3, 4],[5, 6]])

In [36]:
X2 = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

In [37]:
X1.shape[1] == X2.shape[0] # [1]-столбцы. [0]-строки

True

In [38]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [39]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [40]:
Z.shape

(3, 4)

In [ ]:
# как получен элемент матрицы Z нулевой строки нулевого столбца

In [41]:
Z[0, 0]

29

In [43]:
X1[0, 0] * X2[0, 0] + X1[0, 1] * X2[1, 0]

29

In [ ]:
# возведение матрицы в квадрат: numpy.linalg

In [45]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [46]:
A_square = np.dot(A, A)
A_square

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [47]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Создание единичой матрицы

единичная матрица это квадратная матрица которая имеет единицы по главной диогонали а все остальные ячейки заполнены нулями. создается функцией np.eye() в качестве параметра задается пазмерность

In [49]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# умножение любой матрицы на еденичную матрицу дает исходную матрицу


In [55]:
A = np.array([[1, 2],[3, 4],[5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [52]:
np.dot(A, I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [53]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Транспорирование матрицы - строки матрицы становятся столбцами а столбцы строками

In [57]:
A = np.array([[11, 13],[16, 9],[8, 15]])
A

array([[11, 13],
       [16,  9],
       [ 8, 15]])

In [59]:
At = A.transpose()
At

array([[11, 16,  8],
       [13,  9, 15]])

In [60]:
At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

In [61]:
# Рассмотрим матрицы X Y
X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[0, 1], [3, 4], [6, 7], [2, 5]])


In [63]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
Y

array([[0, 1],
       [3, 4],
       [6, 7],
       [2, 5]])

In [66]:
Yt = Y.T
Yt

array([[0, 3, 6, 2],
       [1, 4, 7, 5]])

In [67]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
np.dot(X, Yt)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

Выисления определителя и ранга матрицы

In [72]:
A = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [73]:
# определитель
np.linalg.det(A)

0.0

In [74]:
#ранг матрицы говорит наам о том сеолько столбцов или строк являються линейно независимыми
np.linalg.matrix_rank(A)

2

In [75]:
B = np.array([[7, 4, 5], [8, 3, 2], [6,10, 12]])

In [78]:
np.linalg.det(B)

85.99999999999997

In [77]:
np.linalg.matrix_rank(B)

3

Если матрица не квадратная то можно узнать только ранг

In [79]:
# вычисления обратной матрицы. обратная матрица это матрица которая при умножении на исходную матрицу дает еденичную матрицу

B = np.array([[7, 4, 5], [8, 3, 2], [6, 10, 12]])

In [80]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

свойство обратной матрицы при еще одной конвертации через inv получаем исходную

In [81]:
B_inv2 = np.linalg.inv(B_inv)
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

# Автоматическое создание массивов

In [82]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.arange(2, 12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
# задаем шаг 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [87]:
# в обратном порядке отрицательное значение
np.arange(10, 0, -1)


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [88]:
# дробный шаг
np.arange(0, 10, 0.1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [89]:
# numpy.linspace - то же самое но нужно учитывать что правая граница
# будет включена. Вместо шагов указываем число елементов (100)

np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

numpy.logspace - обе границы тоже включены. но это не сами числа, а степени числа 10

In [90]:
np.logspace(0, 3, 4) # 0 - 10 в нулевой степени. 3 - 10 в третьей степени

array([   1.,   10.,  100., 1000.])

In [92]:
# генерация случайных чисел
# numpy.random.sample - случайные числа с равномерным распределением в промежутке (0.0, 1.0)

np.random.sample(3)


array([0.01471279, 0.8133209 , 0.51091845])

In [93]:
# двумерный массив 2x3

np.random.sample((2, 3)) # из кортежа

array([[0.2134782 , 0.32820742, 0.91030862],
       [0.48666985, 0.60478927, 0.74115106]])

массив 48х64х3(например это может быть случайное изображение с высотой 48. шириной 64. и 3 цветов для каждого пикселя)

In [94]:
np.random.sample((48, 64, 3))

array([[[0.45473796, 0.65450327, 0.95086268],
        [0.29019452, 0.8819784 , 0.98895167],
        [0.41656312, 0.54987064, 0.18183914],
        ...,
        [0.57327335, 0.34954527, 0.56851765],
        [0.01405914, 0.23101153, 0.31525074],
        [0.53635786, 0.84978021, 0.32698033]],

       [[0.66770696, 0.06380847, 0.59362396],
        [0.06124319, 0.27258325, 0.1511916 ],
        [0.97044841, 0.18073735, 0.32443999],
        ...,
        [0.75957489, 0.72614624, 0.98221956],
        [0.23182035, 0.26934296, 0.35804328],
        [0.30554807, 0.48699553, 0.64365991]],

       [[0.17879834, 0.40478353, 0.49620354],
        [0.4103984 , 0.37586697, 0.19734117],
        [0.19878832, 0.77190464, 0.8683357 ],
        ...,
        [0.02947311, 0.23570816, 0.77041113],
        [0.35684325, 0.79173828, 0.69291022],
        [0.92113503, 0.00724053, 0.607586  ]],

       ...,

       [[0.44757016, 0.31304694, 0.05089779],
        [0.96335048, 0.17570579, 0.60479092],
        [0.40131803, 0

numpy.random.randn - (случайные числа с нормальным распределением, среднее значение = 0. отклонение = 1)

In [95]:
np.random.randn(10)

array([ 0.80583825,  1.52787644,  1.20159965,  0.83805462,  1.01122986,
       -1.86852312, -2.41333898, -0.06081063, -0.2300149 ,  0.6318501 ])

In [96]:
np.random.randn(3, 4)

array([[ 0.38782599, -0.51538133,  0.09105747,  1.23741806],
       [-0.59821798,  0.17531463, -0.37799718,  1.12714667],
       [-1.01273125, -0.58502372,  0.47120693,  0.30302792]])

np.random.randint - массив из целых чисел.

In [97]:
np.random.randint(0, 100, 10)

array([87, 25, 94, 48, 84,  0,  9, 59, 87, 80])

In [98]:
# двумерный массив 3х4 из случайных целых чисел в промежутке(0, 10)
np.random.randint(0, 10, (3, 4))

array([[7, 3, 2, 0],
       [7, 5, 3, 5],
       [3, 0, 5, 0]])

np.random.choice-случайный выбор элементов из массива

In [99]:
b = np.array([1, 5, 2, 7, 3, 8, 6, 4])

In [100]:
np.random.choice(b)

5

In [101]:
np.random.choice(b, 3) 

array([4, 6, 5])

в модуле рендом мы получаем псевдо случайные числа

np.random.seed - инициализация генератора случайных чисел.
может использоваться для последующей воспроизводимости(будут генерироваться одинаковые числа)

In [102]:
np.random.seed(42)

In [103]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

In [104]:
# изменения формы массива

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [105]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
#можно указать требуемое число строк а вместо столбцов поставить -1
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
# указать только число столбцов
np.reshape(a, (-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [111]:
# inplace - на месте
a.resize(3, 4)

In [112]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
# из одномерного массива в двумерный
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

соединения массивов

In [115]:
# для наглядности ввозьмем два массива с нулями и единицами
a = np.zeros((2, 3))
a


array([[0., 0., 0.],
       [0., 0., 0.]])

In [116]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [117]:
# соединение строк вертикально
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [118]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [120]:
np.concatenate((a, b), axis=0) # axis 0 нулевая ось в массиве тоесть строка

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
# соединение горизонтально. столбцов

h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [122]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [123]:
np.concatenate((a, b), axis=1) #ось 1 столбцы

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Соединение в глубину(в третьем измерении)

In [124]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

# Фукции для работы с данными

In [3]:
# выбор данных
a = np.random.randint(0, 20, 10)
a

array([12,  1,  3,  2, 15, 19, 11,  3,  3,  1])

In [126]:
a[a > 10] # выбираем из массива числа больше 10

array([18, 11])

In [127]:
a[(a > 10) & (a % 2 == 0)] # оба условия соблюдены

array([18])

In [128]:
a[(a > 10) | (a % 3 == 0)] # одно из условий

array([ 6, 18,  3, 11])

np.where

In [129]:
a

array([ 6, 18, 10, 10,  3,  7,  2,  1, 11,  5])

In [131]:
np.where(a > 10) # возвращает индексы чисел

(array([1, 8], dtype=int64),)

In [132]:
a[np.where(a > 10)] # возвращают сами числа

array([18, 11])

In [4]:
# второй вариант приминения 
a = [1, 4, 7]
b = [9, 2, 5]

In [134]:
# если в условии true то берем элемент из массива а
# если в условии false то берем элемент из массива b
np.where([True, False, True], a,b)

array([1, 2, 7])

In [5]:
# сортировка
a = np.array([[1, 3, 9, 9], [5, 0, 1, 5], [2, 7, 3, 5]])

In [6]:
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [7]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [8]:
a[a[:, 0]. argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [ ]:
# Cлучайное перемешивание массивов

In [10]:
# одномерные массивы
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# inplace - на месте
np.random.shuffle(a)
a

array([1, 0, 4, 5, 9, 8, 2, 7, 3, 6])

In [12]:
# Двумерные массивы
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
#inplace
np.random.shuffle(a) #перемешиваются только строки
a

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [15]:
# математические действия с массивами
# применеие мат функций ко всему массиву
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# логорифм по основанию у
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [17]:
# экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [18]:
a.sum()

21

In [19]:
a.sum(axis=0)  # axis=0 столбец 

array([5, 7, 9])

In [20]:
a.sum(axis=1) # axis=1 строка

array([ 6, 15])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

In [23]:
#поэлементное умножение матриц - не путать с матричным
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Broadcasting(на примере сложения)

In [26]:
a = np.array([[2, 5], [3, 4], [6, 1]])

In [27]:
#совпадает только количество столбцов
b = np.array([1, 2])

к каждой строке массива а прибавляется массив б

In [28]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

In [30]:
# совпадает только количество строк
c = np.array([[1],[2],[3]])

строка массива с прибавляется к каждому столбцу массива а

In [31]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

статистические функции

In [34]:
a = np.random.randint(0, 12, (3, 4))
a

array([[7, 3, 9, 2],
       [2, 8, 7, 6],
       [4, 6, 2, 2]])

In [35]:
a.min() # минимальное значения всех чисел

2

In [36]:
# минимум для каждого столбца
a.min(axis = 0) 

array([2, 3, 2, 2])

In [37]:
# максимум по каждой строке
a.max(axis = 1) 

array([9, 8, 6])

In [38]:
a.mean(axis = 0) #среднее знаение по каждому столбцу

array([4.33333333, 5.66666667, 6.        , 3.33333333])

In [39]:
a.std(axis = 0) #средне квадратичная ошибка по столбцам

array([2.05480467, 2.05480467, 2.94392029, 1.88561808])

Запись и чтение массива из файла

In [40]:
np.save('a.npy', a) # save

In [41]:
b = np.load('a.npy')

In [42]:
b

array([[7, 3, 9, 2],
       [2, 8, 7, 6],
       [4, 6, 2, 2]])